### ISSUE TITLE
5 - Fluid Typography - vanilla

### ISSUE THREAD

**Issue by FrontEndCoder23** [jsartisan/frontend-challenges#338]
styles.css
```css styles.css
body {
  font-family: sans-serif;
}

:root {
  --minVw: 320px;
  --maxVw: 720px;
  --minSize: 16px;
  --maxSize: 32px;
}

h1 {
  font-size: clamp(var(--minSize), calc((var(--maxSize) - var(--minSize)) / (var(--maxVw) - var(--minVw)) * (100vw - var(--minVw)) + var(--minSize), var(--maxSize));
}

```
