### ISSUE TITLE
Escape the overflow hidden

### ISSUE THREAD

**Issue by jsartisan** [jsartisan/frontend-challenges#340]
## Info

```yaml
difficulty: medium
title: Escape the overflow hidden
type: question
template: static
tags: css, javascript
```

## Question

You have a parent container box that has a condition of `overflow: hidden` and there is a rocket emoji in it.

```html
<div class="parent">
  <div class="rocket">🚀</div>
</div>
```
Your task is to show a rocket emoji in top right corner. `-25px` from top and `25px` from right. It will look like this:

![CleanShot 2024-11-11 at 09 31 03](https://github.com/user-attachments/assets/1f34f05b-4e59-4ecc-838b-66351298cd93)

The only condition is that you can't remove `oveflow: hidden` on parent.

## Template

index.html
```html index.html
<!doctype html>
<html>
  <head>
    <title>Parcel Sandbox</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="/styles.css" />
    <link rel="stylesheet" href="/demo.css" />
  </head>

  <body>
    <div class="parent">
      <div class="rocket">🚀</div>
    </div>
  </body>
</html>

```

styles.css
```css styles.css
.parent {
  height: 200px;
  width: 200px;
  border: 2px solid black;
  overflow: hidden;
  position: relative;
}

.rocket {
  height: 50px;
  width: 50px;
  font-size: 50px;
}
```

package.json hidden
```json package.json
{
  "dependencies": {},
  "main": "/index.html",
  "devDependencies": {}
}
```

demo.css hidden
```css demo.css
html, body {
  height: 100%;
  width: 100%;
  margin: 0;
}

body {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
