### ISSUE TITLE
340 - Escape the overflow hidden - static

### ISSUE THREAD

**Issue by jsartisan** [jsartisan/frontend-challenges#342]
styles.css
```css styles.css
.parent {
  height: 200px;
  width: 200px;
  border: 2px solid black;
  background-color: yellow;
  overflow: hidden;
  position: relative;
}

.rocket {
  height: 50px;
  width: 50px;
  font-size: 50px;
  position: fixed;
}

.absolute {
  position: absolute;
  right: 25px;
  top: -25px;
}
```

index.html
```html index.html
<!doctype html>
<html>
  <head>
    <title>Parcel Sandbox</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="/styles.css" />
    <link rel="stylesheet" href="/demo.css" />
  </head>

  <body>
    <div class="parent">
      <div class="absolute">
        <div class="rocket">🚀</div>
      </div>
    </div>
  </body>
</html>

```
