### ISSUE TITLE
Layout 1

### ISSUE THREAD

**Issue by jsartisan** [jsartisan/frontend-challenges#40]
## Info

```yaml
difficulty: easy
title: Layout 1
template: vanilla
tags: css
```

## Question

You are given a container with 6 children divs. Implement the layout as shown in the video:

https://github.com/jsartisan/frontend-challenges/assets/6636360/b837567c-66b5-45f5-b289-d6167c849af9

The breakpoints are 400px, 600px, 800px. 

## Template

styles.css
```css styles.css
.container {
 
}

.item {
  background: #e1e1e1;
  height: 100px;
}
```

index.js
```js index.js
import "./styles.css";

```

index.html
```html index.html
<!DOCTYPE html>
<html>

<head>
  <title>Parcel Sandbox</title>
  <meta charset="UTF-8" />
</head>

<body>
  <div class="container">
    <div class="item"></div>
    <div class="item"></div>
    <div class="item"></div>
    <div class="item"></div>
    <div class="item"></div>
    <div class="item"></div>
  </div>
</body>

</html>
```
