### ISSUE TITLE
40 - Layout 1

### ISSUE THREAD

**Issue by jsartisan** [jsartisan/frontend-challenges#42]
styles.css
```css styles.css
.container {
  display: grid;
  gap: 0.5rem;
}

.item {
  background: #e1e1e1;
  height: 100px;
}

@media (width >= 400px) {
  .container {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (width >= 600px) {
  .container {
    grid-template-columns: repeat(12, 1fr);
  }

  .item {
    grid-column: span 6;
  }
  
  .item:nth-child(1), .item:nth-child(6) {
    grid-column: span 12;
  }
}

@media (width >= 800px) {
  .item {
    grid-column: span 3;
  }
  
  .item:nth-child(1), .item:nth-child(6) {
    grid-column: span 6;
  }
}
```
