### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by jsartisan** [jsartisan/frontend-challenges#47]
## Info

```yaml
difficulty: medium
title: Checkbox
template: vanilla
tags: css, design-system, html
```

## Question

One common UI element found in many web applications is a checkbox. While HTML provides a built-in checkbox element, sometimes we need to create custom checkboxes to better suit the design or functionality requirements of our application.

![Checkbox States](https://design.gs.com/checkboxes-states.png)

Create a custom checkbox component using HTML, CSS, and JavaScript. The component should have the following features:

- Display a custom checkbox icon. 
- Allow toggling between checked and unchecked states when clicked.
- Allow states like hover, focus, intermediate and disabled.
- Allow `small`, `medium` and `large` size variants.

## Template

styles.css
```css styles.css
body {
  font-family: sans-serif;
}

h1 {
  font-size: 1.5rem;
}
```

index.js
```js index.js
import "./styles.css";

```

index.html
```html index.html
<!DOCTYPE html>
<html>

<head>
  <title>Parcel Sandbox</title>
  <meta charset="UTF-8" />
</head>

<body>
  <label class="checkbox">
    <input type="checkbox" checked="true" />
    Label
  </label>
</body>

</html>
```
