### ISSUE TITLE
Two functions - one object

### ISSUE THREAD

**Issue by jsartisan** [jsartisan/frontend-challenges#69]
## Info

```yaml
difficulty: easy
title: Two functions - one object
type: question
template: javascript
tags: javascript, objects
```

## Question

Is it possible to create two constructor functions, A and B, such that new A() is equal to new B() when compared using the == operator?

Given the following setup:

```js
function A() { ... }
function B() { ... }

let a = new A();
let b = new B();

alert(a == b); // true
```

Provide the implementations for A and B that satisfy the condition a == b.

## Template

index.js
```js index.js
export function A() {
   // your code here
}

export function B() {
   // your code here
}
```

index.test.js
```js index.test.js
import { A, B } from './';

describe('Constructor Functions A and B', () => {
  test('new A() should equal new B()', () => {
    let a = new A();
    let b = new B();

    expect(a).toBe(b);
  });
});
```
